# Generated by Django 3.2.18 on 2023-03-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redirect_url', models.CharField(max_length=2048, unique=True)),
                ('url_name', models.CharField(blank=True, max_length=256, null=True)),
                ('short_url', models.CharField(max_length=32, unique=True)),
                ('redirect_count', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
