# Generated by Django 3.2.18 on 2023-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcollection',
            name='short_url',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
