# Generated by Django 3.2.18 on 2023-03-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_alter_urlcollection_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlcollection',
            name='redirect_url',
            field=models.URLField(max_length=2048, unique=True),
        ),
    ]
